# Generated by Django 3.2.18 on 2023-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
